# Generated by Django 4.2.5 on 2023-10-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0002_passname'),
    ]

    operations = [
        migrations.AddField(
            model_name='passname',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='password_generator.user'),
        ),
    ]
