# Generated by Django 4.2.5 on 2023-10-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_generator', '0003_passname_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Costumer',
        ),
    ]
